<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">


    <!-- ################# Properties ################ -->
    <!-- ############################################# -->

        <xacro:property name="deg_to_rad" value="0.017453293" />
        
        <xacro:property name="mir_100_base_mass" value="58.0" />

        <xacro:property name="mir_100_act_wheel_radius" value="0.0625" />
        <xacro:property name="mir_100_act_wheel_width" value="0.032" />
        <xacro:property name="mir_100_act_wheel_mass" value="1.0" />
        <xacro:property name="mir_100_act_wheel_dx" value="0.037646" />
        <xacro:property name="mir_100_act_wheel_dy" value="0.222604" />

        <xacro:property name="mir_100_caster_wheel_radius" value="${mir_100_act_wheel_radius}" />
        <xacro:property name="mir_100_caster_wheel_width" value="${mir_100_act_wheel_width}" />
        <xacro:property name="mir_100_caster_wheel_mass" value="${mir_100_act_wheel_mass}" />
        <xacro:property name="mir_100_caster_wheel_dx" value="-0.0382" />
        <xacro:property name="mir_100_caster_wheel_dy" value="0" />
        <xacro:property name="mir_100_caster_wheel_dz" value="-0.094" />
        <xacro:property name="mir_100_front_caster_wheel_base_dx" value="0.341346" />
        <xacro:property name="mir_100_back_caster_wheel_base_dx" value="-0.270154" />
        <xacro:property name="mir_100_caster_wheel_base_dy" value="0.203" />
        <xacro:property name="mir_100_caster_wheel_base_dz" value="${mir_100_caster_wheel_radius-mir_100_caster_wheel_dz}" />

        <xacro:property name="imu_stdev" value="0.00017" />
        <xacro:property name="imu_update_rate" value="50" />

        <xacro:property name="wheel_separation" value="0.445208" />
        <xacro:property name="wheel_radius" value="0.0625" />


    <!-- ############################################# -->
    <!-- ################# Properties ################ -->

       
    <!-- #################### Macros ################### -->
    <!-- ############################################### -->

        <xacro:macro name="actuated_wheel" params="locationprefix locationright">

            <joint name="MiR__base_${locationprefix}_wheel_joint" type="continuous">
                <origin xyz="0.0 ${-mir_100_act_wheel_dy * locationright} ${mir_100_act_wheel_radius}" rpy="0 0 0" />
                <parent link="MiR_base_link" />
                <child link="MiR_${locationprefix}_wheel_link" />
                <axis xyz="0 1 0" />
                <limit effort="100" velocity="20.0" />
            </joint>

            <link name="MiR_${locationprefix}_wheel_link">
                <xacro:cylinder_inertial mass="${mir_100_act_wheel_mass}" radius="${mir_100_act_wheel_radius}" length="${mir_100_act_wheel_width}">
                <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
                </xacro:cylinder_inertial>
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://mir100_mobile_base/mesh/visual/wheel.stl" />
                    </geometry>
                    <xacro:insert_block name="material_dark_grey" />
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://mir100_mobile_base/mesh/visual/wheel.stl" />
                    </geometry>
                </collision>
            </link>

        </xacro:macro>
        
        <xacro:macro name="caster_hub" params="locationprefix locationright wheel_base_dx">

            <joint name="MiR__base_${locationprefix}_caster_rotation_joint" type="continuous">
                <origin xyz="${wheel_base_dx} ${-mir_100_caster_wheel_base_dy * locationright} ${mir_100_caster_wheel_base_dz}" rpy="0 0 0" />
                <parent link="MiR_base_link" />
                <child link="MiR_${locationprefix}_caster_rotation_link" />
                <axis xyz="0 0 1" />
                <dynamics damping="0.01" friction="0.0"/>
            </joint>

            <link name="MiR_${locationprefix}_caster_rotation_link">
                <inertial>
                    <!-- <origin xyz="0 0 -0.042500000044" rpy="${0.5 * pi} ${24 * deg_to_rad} ${1.5 * pi}" /> -->
                    <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
                    <mass value="0.3097539019" />
                    <inertia
                    ixx="0.0005844517978"
                    ixy="0"
                    ixz="0"
                    iyy="0.00052872551237"
                    iyz="0"
                    izz="0.00017923555074" />
                </inertial>
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://mir100_mobile_base/mesh/visual/caster_wheel_base.stl" />
                    </geometry>
                    <xacro:insert_block name="material_silver" />
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://mir100_mobile_base/mesh/collision/caster_wheel_base.stl" />
                    </geometry>
                </collision>
            </link>

        </xacro:macro>

        <xacro:macro name="caster_wheel" params="locationprefix locationright wheel_base_dx">

            <joint name="MiR__base_${locationprefix}_caster_wheel_joint" type="continuous">
                <origin xyz="${mir_100_caster_wheel_dx} ${-mir_100_caster_wheel_dy * locationright} ${mir_100_caster_wheel_dz}" rpy="0 0 0" />
                <parent link="MiR_${locationprefix}_caster_rotation_link" />
                <child link="MiR_${locationprefix}_caster_wheel_link" />
                <axis xyz="0 1 0" />
            </joint>

            <link name="MiR_${locationprefix}_caster_wheel_link">
                <xacro:cylinder_inertial mass="${mir_100_caster_wheel_mass}" radius="${mir_100_caster_wheel_radius}" length="${mir_100_caster_wheel_width}">
                    <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
                </xacro:cylinder_inertial>
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://mir100_mobile_base/mesh/visual/wheel.stl" />
                    </geometry>
                    <xacro:insert_block name="material_dark_grey" />
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://mir100_mobile_base/mesh/visual/wheel.stl" />
                    </geometry>
                </collision>
            </link>

        </xacro:macro> 

        <xacro:macro name="MiR100_mobile_robot" params="parent">

            <joint name="MiR__base_joint_fixed" type="fixed">
                <parent link="${parent}" />
                <child link="MiR_base_link" />
                <origin xyz="0 0 0" rpy="0 0 0" />
            </joint>

            <link name="MiR_base_link">
                <xacro:box_inertial mass="${mir_100_base_mass}" x="0.9" y="0.58" z="0.3">
                    <origin xyz="${mir_100_act_wheel_dx} 0 0.20" rpy="0 0 0" />
                </xacro:box_inertial>
                <visual>
                    <origin xyz="${mir_100_act_wheel_dx} 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://mir100_mobile_base/mesh/visual/mir_100_base.stl" />
                    </geometry>
                    <xacro:insert_block name="material_white" />
                </visual>
                <collision>
                    <origin xyz="${mir_100_act_wheel_dx} 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="package://mir100_mobile_base/mesh/collision/mir_100_base.stl" />
                    </geometry>
                </collision>
            </link>


            <xacro:actuated_wheel locationprefix="left" locationright="-1"/>
            <xacro:actuated_wheel locationprefix="right" locationright="1"/>

            <xacro:caster_hub locationprefix="fl" locationright="-1" wheel_base_dx="${mir_100_front_caster_wheel_base_dx}"/>
            <xacro:caster_wheel locationprefix="fl" locationright="-1" wheel_base_dx="${mir_100_front_caster_wheel_base_dx}"/>

            <xacro:caster_hub locationprefix="fr" locationright="1" wheel_base_dx="${mir_100_front_caster_wheel_base_dx}"/>
            <xacro:caster_wheel locationprefix="fr" locationright="1" wheel_base_dx="${mir_100_front_caster_wheel_base_dx}"/>

            <xacro:caster_hub locationprefix="bl" locationright="-1" wheel_base_dx="${mir_100_back_caster_wheel_base_dx}"/>
            <xacro:caster_wheel locationprefix="bl" locationright="-1" wheel_base_dx="${mir_100_back_caster_wheel_base_dx}"/>

            <xacro:caster_hub locationprefix="br" locationright="1" wheel_base_dx="${mir_100_back_caster_wheel_base_dx}"/>
            <xacro:caster_wheel locationprefix="br" locationright="1" wheel_base_dx="${mir_100_back_caster_wheel_base_dx}"/>


            <joint name="MiR__base_to_surface_joint_fixed" type="fixed">
                <origin xyz="${mir_100_act_wheel_dx} 0 0.352" rpy="0 0 0" />
                <parent link="MiR_base_link" />
                <child link="MiR_surface" />
                <axis xyz="0 0 1" />
            </joint>

            <link name="MiR_surface"/>


            <!-- IMU -->

                <joint name="MiR__base_to_imu_joint_fixed" type="fixed">
                    <parent link="MiR_base_link" />
                    <child link="MiR_imu_link" />
                    <origin xyz="0.0 0.0 0.25" rpy="0 0 0" />  <!-- same as real MiR -->
                </joint>

                <link name="MiR_imu_link" />

                <!-- Create an alias for imu_link. This is necessary because the real MiR's
                    TF has imu_link, but the imu_data topic is published in the imu_frame
                    frame. -->
                    <joint name="MiR__imu_link_to_imu_frame_joint_fixed" type="fixed">
                        <parent link="MiR_imu_link" />
                        <child link="MiR_imu_frame" />
                        <origin xyz="0 0 0" rpy="0 0 0" />
                    </joint>

                <link name="MiR_imu_frame" />

            <!-- Laser scanners -->

                <link name="MiR_front_laser_link">
                    <visual>
                        <origin xyz="0.0 0.0 0.0" rpy="${pi} 0 0" />
                        <geometry>
                            <mesh filename="package://mir100_mobile_base/mesh/visual/sick_lms-100.stl" />
                        </geometry>
                        <xacro:insert_block name="material_black" />
                    </visual>
                    <collision>
                        <origin xyz="0.0 0.0 0.0" rpy="${pi} 0 0" />
                        <geometry>
                            <mesh filename="package://mir100_mobile_base/mesh/visual/sick_lms-100.stl" />
                        </geometry>
                    </collision>
                    <xacro:box_inertial x="0.156" y="0.155" z="0.185" mass="2.0">
                        <origin xyz="0 0 0" />
                    </xacro:box_inertial>
                </link>

                <joint name="MiR__base_to_front_laser_joint_fixed" type="fixed">
                    <parent link="MiR_base_link" />
                    <child link="MiR_front_laser_link" />
                    <origin xyz="0.4288 0.2358 0.1914" rpy="0.0 0.0 ${0.25 * pi}" />  <!-- from visually matching up the meshes of the MiR and the laser scanner -->
                </joint>

                <link name="MiR_back_laser_link">
                    <visual>
                        <origin xyz="0.0 0.0 0.0" rpy="${pi} 0 0" />
                        <geometry>
                            <mesh filename="package://mir100_mobile_base/mesh/visual/sick_lms-100.stl" />
                        </geometry>
                        <xacro:insert_block name="material_black" />
                    </visual>
                    <collision>
                        <origin xyz="0.0 0.0 0.0" rpy="${pi} 0 0" />
                        <geometry>
                            <mesh filename="package://mir100_mobile_base/mesh/visual/sick_lms-100.stl" />
                        </geometry>
                    </collision>
                    <xacro:box_inertial x="0.156" y="0.155" z="0.185" mass="2.0">
                        <origin xyz="0 0 0" />
                    </xacro:box_inertial>
                </link>

                <joint name="Mir__base_to_back_laser_joint_fixed" type="fixed">
                    <parent link="MiR_base_link" />
                    <child link="MiR_back_laser_link" />
                    <origin xyz="-0.3548 -0.2352 0.1914" rpy="0.0 0.0 ${-0.75 * pi}" />  <!-- from visually matching up the meshes of the MiR and the laser scanner -->
                </joint>

            <!-- Ultrasound sensors -->

                <link name="MiR_right_us_frame" />

                <joint name="MiR__base_to_right_us_joint_fixed" type="fixed">  
                    <parent link="MiR_base_link" />
                    <child link="MiR_right_us_frame" />
                    <origin xyz="0.45 -0.12 0.16 " rpy="0 0 0" />  <!-- from visually matching to the mesh of the MiR -->
                </joint>

                <link name="MiR_left_us_frame" />

                <joint name="MiR__base_to_left_us_joint_fixed" type="fixed">   
                    <parent link="MiR_base_link" />
                    <child link="MiR_left_us_frame" />
                    <origin xyz="0.45 0.12 0.16 " rpy="0 0 0" />  <!-- from visually matching to the mesh of the MiR -->
                </joint>

        </xacro:macro>
 
    <!-- ############################################### -->
    <!-- #################### Macros ################### -->
</robot>